name: Quality Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Just
        run: |
          sudo snap install just --classic

      - name: Install Terraform / Terragrunt
        run: |
          sudo snap install terraform --classic
          sudo snap install terragrunt --classic

      - name: Run lint checks
        run: just lint
