name: Quality Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - modules/**
  push:
    branches:
      - main
    paths:
      - modules/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Terraform
        run: sudo snap install terraform --classic

      - name: Terraform format lint
        working-directory: ./modules
        run: terraform fmt -check -recursive -diff
