name: Quality Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format lint
        run: terraform fmt -check -recursive -diff

      - name: Terragrunt HCL format lint
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: "1.11.3"
          tg_version: "0.67.10"
          tg_command: "hclfmt --terragrunt-check --terragrunt-diff"

